[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@solidity-json-writer/=lib/solidity-json-writer/",
]
gas_reports = ["*"]
[etherscan]
sepolia = { key = "${ETHERSCAN__API_KEY}", name = "58008", url = "https://api-sepolia.etherscan.io/api" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
